logger:
  level: <%= ENV.fetch('LOGGER_LEVEL') { 'warn' } %>

thron:
  client_id: <%= ENV.fetch('THRON_CLIENT_ID') { 'none' } %>
  base_url: <%= ENV.fetch('THRON_BASE_URL') { "-view.4me.it/api" } %> 

