logger:
  verbose: <%= ENV.fetch('VERBOSE') { false } %>
  level: <%= ENV.fetch('LOGGER_LEVEL') { 'warn' } %>

thron:
  client_id: <%= ENV.fetch('THRON_CLIENT_ID') { 'none' } %>
  protocol: <%= ENV.fetch('THRON_PROTOCOL') { 'https' } %>
